<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>ModelExplorer</AssemblyName>
    <RootNamespace>ModelExplorer.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Wpf.SharpDX" Version="3.1.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModelExplorer.Geometry\ModelExplorer.Geometry.csproj" />
    <ProjectReference Include="..\ModelExplorer.Indexing\ModelExplorer.Indexing.csproj" />
  </ItemGroup>

</Project>
