<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ModelExplorer.Indexing</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModelExplorer.Geometry\ModelExplorer.Geometry.csproj" />
  </ItemGroup>

</Project>
